Description of dsUnitSaveAutoGenTestData
Home > functions > internal > unit-test > dsUnitSaveAutoGenTestData.m
dsUnitSaveAutoGenTestData
PURPOSE
Inputs:
SYNOPSIS
function dsUnitSaveAutoGenTestData(argin, argout, localFn_flag)
DESCRIPTION
 Inputs:
   argin: cell array with input arguments
   argout: cell array with output arguments
   localFn_flag: logical of whether to include 'fn1__fn2' in fnName or 'fn1'
CROSS-REFERENCE INFORMATION
This function calls:
dsGetConfig GETCONFIG - returns the value of the variable specificed as string in argument
This function is called by:
dsImport DSIMPORT - load data into DynaSim formatted data structure.
dsApplyModifications APPLYMODIFICATIONS - Apply modifications to DynaSim specification or model structure
dsCalcACF CALCACF - Calculate the autocorrelation function.
dsCalcAverages CALCAVERAGES - Average fields in a DynaSim data struct across neurons
dsCalcCellProperties CALCCELLPROPERTIES - calculates the intrinsic electrophysiological properties of all cells in one or more populations
dsCalcFR CALCFR - Calculate firing rage for DynaSim data
dsCalcFRmulti CALCFRMULTI - extends dsCalcFR to get SUA and MUA firing rates
dsCalcISI CALCISI - Calculate the interspike interval.
dsCalcPower CALCPOWER - Compute spectral analysis of DynaSim data
dsCalcSpikeSync CALCSPIKESYNC - Compute spike synchronization between spiketrains
dsCalcSumOverFields CALCSUMOVERFIELDS - Creates a new field in data that is the sum of a bunch of other fields
dsCheckCovary CHECKCOVARY - TODO I assume this checks if any varied parameters are covaried?
dsCheckData CHECKDATA - Standardize data structure and auto-populate missing fields
dsCheckHostPaths CHECKHOSTPATHS - Compare paths on host to those set in studyinfo when batch was created
dsCheckModel CHECKMODEL - Standardize model structure and auto-populate missing fields
dsCheckSpecification CHECKSPECIFICATION - standardize specification structure and auto-populate missing fields
dsClassifyEquation CLASSIFYEQUATION - use regular expressions to classify model expressions in STRING
dsCollectVariedParams COLLECTVARIEDPARAMS - Gathers info on parameters that have been varied in a batch
dsCombineModels COMBINEMODELS - combine subfields in two DynaSim model structures
dsDynasim2odefun Purpose: prepare ODEFUN for use with built-in Matlab solvers.
dsGenerateModel GENERATEMODEL - Parse DynaSim specification and organize model data in DynaSim model structure
dsGetParentNamespace GETPARENTNAMESPACE - determine parent namespace from namespace specified in namespace
dsParseModelEquations PARSEMODELEQUATIONS - parse equations and organize model data in DynaSim model structure
dsPropagateFunctions PROPAGATEFUNCTIONS - eliminate internal function calls from model ODEs, ICs, monitors, and conditionals.
dsPropagateNamespaces PROPAGATENAMESPACES - namespace-establishing namespace substitutions.
dsPropagateParameters PROPAGATEPARAMETERS - substitute parameter values or prepend parameter names with prefix across all model equations.
dsSelectVariables SELECTVARIABLES - determine what variables to plot
dsStrrep STRREP - replace full words by new character strings, ignoring matches that appear as sub-strings.
dsStrrep2 STRREP2 - replace full words by new character strings, WITHOUT ignoring matches that appear as sub-strings.
dsUnitSaveAutoGenTestDataLocalFn % saveAutoGenTestDataLocalFn(argin, argout)
SOURCE CODE
function dsUnitSaveAutoGenTestData(argin, argout, localFn_flag)
% Inputs:
%   argin: cell array with input arguments
%   argout: cell array with output arguments
%   localFn_flag: logical of whether to include 'fn1__fn2' in fnName or 'fn1'
if ~exist('localFn_flag','var')
  localFn_flag = false;
end
% get fn name from stack
stack = dbstack;
if ~localFn_flag
  fnNameStack = stack(2).name;
  fnName = fnNameStack;
else
  fnNameStack = stack(4).name;
  fnName = [fnNameStack '__' stack(3).name];
end
hash = DataHash(argin);
testFileName = sprintf('%s_autogen_%s.mat', fnName, hash);
testFileDir = fullfile(dsGetConfig('ds_unitTestData_path'), 'autogen_newSave');
mkdirSilent(testFileDir);
testFilePath = fullfile(testFileDir, testFileName);
save(testFilePath, 'argin', 'argout')
end