Description of dsUnitTest_checkModel
Home > functions > internal > unit-test > dsUnitTest_checkModel.m
dsUnitTest_checkModel
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
dsCheckModel CHECKMODEL - Standardize model structure and auto-populate missing fields
dsGetConfig GETCONFIG - returns the value of the variable specificed as string in argument
dsUnitTest_checkModel
This function is called by:
dsUnitTest_checkModel
SUBFUNCTIONS
function testCellIn(testCase)
SOURCE CODE
classdef dsUnitTest_checkModel < matlab.unittest.TestCase
  properties
    unitTestDataPath = dsGetConfig('ds_unitTestData_path');
  end
  methods (Test,  TestTags = {'core'})
    function testCellIn(testCase)
      argin = {{'s=10; r=27; b=2.666';'dx/dt=s*(y-x)';'dy/dt=r*x-y-x*z';'dz/dt=-b*z+x*y'}};
      expectedOut = load(fullfile(testCase.unitTestDataPath,'checkModel_testCellIn'));
      expectedOut = expectedOut.model;
      testCase.verifyEqual(expectedOut, dsCheckModel(argin{:}) );
    end
  end
end