Description of dsUnitSaveAutoGenTestDataLocalFn
Home > functions > internal > unit-test > dsUnitSaveAutoGenTestDataLocalFn.m
dsUnitSaveAutoGenTestDataLocalFn
PURPOSE
% saveAutoGenTestDataLocalFn(argin, argout)
SYNOPSIS
function dsUnitSaveAutoGenTestDataLocalFn(argin, argout)
DESCRIPTION
% saveAutoGenTestDataLocalFn(argin, argout)
 Purpose: calls `saveAutoGenTestDataLocalFn(argin, argout, 1);`
 Inputs:
   argin: cell array with input arguments
   argout: cell array with output arguments
CROSS-REFERENCE INFORMATION
This function calls:
dsUnitSaveAutoGenTestData Inputs:
This function is called by:
dsApplyModifications APPLYMODIFICATIONS - Apply modifications to DynaSim specification or model structure
dsAutoMergeVarieds [data_new, variedname_merged, varied_vals ] = mergeVarieds(data,varied_fields)
dsCheckCovary CHECKCOVARY - TODO I assume this checks if any varied parameters are covaried?
dsCheckSpecification CHECKSPECIFICATION - standardize specification structure and auto-populate missing fields
dsClassifyEquation CLASSIFYEQUATION - use regular expressions to classify model expressions in STRING
dsGetLinearIndependentDs [Asubs, Abasis, Abasisi] = getLinearIndependentDs(data,ignore_constant_shift,varargin)
dsMergeVarieds [data_new, variedname_merged, varied_vals ] = mergeVarieds(data,varied_fields)
dsPropagateFunctions PROPAGATEFUNCTIONS - eliminate internal function calls from model ODEs, ICs, monitors, and conditionals.
dsPropagateParameters PROPAGATEPARAMETERS - substitute parameter values or prepend parameter names with prefix across all model equations.
SOURCE CODE
function dsUnitSaveAutoGenTestDataLocalFn(argin, argout)
%% saveAutoGenTestDataLocalFn(argin, argout)
% Purpose: calls `saveAutoGenTestDataLocalFn(argin, argout, 1);`
%
% Inputs:
%   argin: cell array with input arguments
%   argout: cell array with output arguments
dsUnitSaveAutoGenTestData(argin, argout, 1);
end