Description of mergeData
mergeData
PURPOSE
MERGEDATA - Merge two Dynasim structures created from different simulations
SYNOPSIS
function data_merged = mergeData(data1,data2)
DESCRIPTION
 MERGEDATA - Merge two Dynasim structures created from different simulations
CROSS-REFERENCE INFORMATION
This function calls:
mergeData MERGEDATA - Merge two Dynasim structures created from different simulations
xPlt2ds % data=xPlt2ds(obj,varargin)
xPlt2dsImage % data=xPlt2ds(obj,varargin)
This function is called by:
mergeData MERGEDATA - Merge two Dynasim structures created from different simulations
SOURCE CODE
function data_merged = mergeData(data1,data2)
    % MERGEDATA - Merge two Dynasim structures created from different simulations
    xp1 = ds.all2xPlt(data1);
    xp2 = ds.all2xPlt(data2);
    xp_merged = mergeData(xp1,xp2);
    xp_merged.meta = xp1.meta; % Warning - need to make sure metadata merges properly; not yet implemented
    % Sort everything except populations and variables
    inds = true(1,ndims(xp_merged));
    inds(xp_merged.findaxis('populations')) = false;
    inds(xp_merged.findaxis('variables')) = false;
    xp_merged = xp_merged.sortAxis(find(inds));
    if isfield(data1,'plot_files') && isfield(data2,'plot_files')
        data_merged = xPlt2dsImage(xp_merged);
    elseif ~isfield(data1,'plot_files') && ~isfield(data2,'plot_files')
        data_merged = xPlt2ds(xp_merged);
    else
        error('Unknown input types');
    end
end