Description of dsAll2mdd
dsAll2mdd
PURPOSE
SYNOPSIS
function [xp,is_image] = dsAll2mdd(data,varargin)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
ds2mdd Convert DynaSim data structure to xp format
dsCheckData CHECKDATA - Standardize data structure and auto-populate missing fields
dsImg2mdd
This function is called by:
dsPlot2 % handles=dsPlot(data,'option',value)
dsMergeData MERGEDATA - Merge two Dynasim structures created from different simulations
SOURCE CODE
function [xp,is_image] = dsAll2mdd(data,varargin)
if ~isfield(data,'plot_files')      % Standard DynaSim data structure
    % Check inputs
    data=dsCheckData(data, varargin{:});
      % note: calling dsCheckData() at beginning enables analysis/plotting functions to
      % accept data matrix [time x cells] in addition to DynaSim data structure.
    % Convert input data to MDD
    xp = ds2mdd(data);
    is_image = 0;
else                            % Structure of links to plots
    % Convert input data to MDD
    data_img=data;
    xp = dsImg2mdd(data_img);
    is_image = 1;
end