Description of dsGetConfig
dsGetConfig
PURPOSE
GETCONFIG - returns the value of the variable specificed as string in argument
SYNOPSIS
function varOutput = dsGetConfig(query)
DESCRIPTION
 GETCONFIG - returns the value of the variable specificed as string in argument
 Usage: pathOutput = getConfig(pathQueryString)
CROSS-REFERENCE INFORMATION
This function calls:
dsGetRootPath getRootPath - get path to main ds directory
dsMakeDefaultConfig dsMakeDefaultConfig - write default DS config vars to disk as text file in main DS dir.
This function is called by:
dsGenerateDocumentation GENERATEDOCUMENTATION - Build DynaSim function documentation
dsUnzipDemoData dsUnzipDemoData - Unzips demo data (utility function)
dsZipDemoData ZIPDEMODATA - Zips demo data (utility function)
dsUnitGetAutogenDirs GETAUTOGENFILES returns cell list of autogen directories, for functions which write files to disk
dsUnitGetAutogenFiles GETAUTOGENFILES returns cell list of autogen files
dsUnitMake_autogenData % Make DynaSim Autogen Files
dsUnitRun_all % Run all tests
dsUnitRun_autogen_all % Run all autogen tests
dsUnitRun_autogen_all_jenkins % Run all autogen tests
dsUnitRun_autogen_dirs % Run autogen dirs tests
dsUnitRun_autogen_non_dirs % Run non-dir non-local autogen tests
dsUnitSaveAutoGenTestData Inputs:
dsUnitSaveAutoGenTestDir Inputs:
dsUnitTest_autogenDirs_all
dsUnitTest_autogen_all
dsUnitTest_autogen_all_localfn
dsUnitTest_autogen_query
dsUnitTest_checkModel
SOURCE CODE
function varOutput = dsGetConfig(query)
% GETCONFIG - returns the value of the variable specificed as string in argument
%
% Usage: pathOutput = getConfig(pathQueryString)
  dsVarsFile = fullfile(dsGetRootPath(),'dsConfig.txt');
  if ~exist(dsVarsFile, 'file')
    dsMakeDefaultConfig(); % bring all path vars into namespace
  end
  fid = fopen(dsVarsFile);
  dsVars = textscan(fid, '%s = %q');
  fclose(fid);
  varCell = dsVars{2}(~cellfun(@isempty,strfind(dsVars{1}, query)));
  if ~isempty(varCell)
    varOutput = varCell{1}; % eval variable string as variable
  else
    varOutput = [];
    if isempty(varOutput); warning('Requested path not found. dsConfig.txt is possibly corrupt. Try deleting dsConfig.txt and running dsMakeDefaultConfig()');
  end
end