Description of dsOptions2Keyval
Home > functions > internal > dsOptions2Keyval.m
dsOptions2Keyval
PURPOSE
OPTIONS2KEYVAL - Convert from options structure to a list of key/value pairs.
SYNOPSIS
function keyval = dsOptions2Keyval(options)
DESCRIPTION
OPTIONS2KEYVAL - Convert from options structure to a list of key/value pairs.
 Usage:
   keyvals = dsOptions2Keyval(options)
 Inputs:
   - options: options structure to convert
 See also: dsCheckOptions
 Author: Jason Sherfey, PhD <jssherfey@gmail.com>
 Copyright (C) 2016 Jason Sherfey, Boston University, USA
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
dsImport DSIMPORT - load data into DynaSim formatted data structure.
dsSimulate % data=dsSimulate(model,'option',value,...)
dsCheckSolverOptions CHECKSOLVEROPTIONS - standardize simulation options appended to params.mat
dsGetSolveFile GETSOLVEFILE - helper function that creates or retrieves the desired solver file.
dsPlotFR2 PLOTFR2 - plot spike rates in various ways depending on what data was provided.
dsPrepareMEX PREPAREMEX - take an m-file path and compile it using the Matlab coder.
SOURCE CODE
function keyval = dsOptions2Keyval(options)
%OPTIONS2KEYVAL - Convert from options structure to a list of key/value pairs.
%
% Usage:
%   keyvals = dsOptions2Keyval(options)
%
% Inputs:
%   - options: options structure to convert
%
% See also: dsCheckOptions
%
% Author: Jason Sherfey, PhD <jssherfey@gmail.com>
% Copyright (C) 2016 Jason Sherfey, Boston University, USA
% Grab the field names
fields = fieldnames(options);
keyval = {};
% Loop over the field names, grab the value, and append both to the output
% list of key/value pairs
for i=1:length(fields)
  keyval{end+1} = fields{i};
  keyval{end+1} = options.(fields{i});
end;